config/routes.rb
Rails.application.routes.draw do
  get 'topics/new'
  get 'sessions/new'
  
  root 'topics#index'
  
  resources :users
  
  get '/login',  to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :topics
  
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
  get '/comments/:topic_id/new' => 'comments#new', as: 'comments'
  post '/comments/:topic_id/create', to: 'comments#create', as:'comments_create'
  get '/comments/:id/edit', to: 'comments#edit', as:'edit_comments'
  patch '/comments/:id', to: 'comments#update', as: 'comments_update'
  delete '/comments', to: 'comments#destroy', as:'comment_delete'
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: {maximum: 100}
  
  
  belongs_to :topic
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user
  
  def new
    @topic = Topic.find_by(params[:topic_id])
    @comment = Comment.new
  end
  
  def create
    @comment = current_user.comments.new(comment_params)
    @comment.topic_id = params[:topic_id]
    
    if @comment.save
      redirect_to topic_path(@comment.topic_id), success: 'コメントを投稿しました'
    else
      flash.now[:danger] = "コメントの投稿に失敗しました"
      Rails.logger.info(@comment.errors.inspect)
      render :new
    end
  end
  
  def edit
    @comment = Comment.find(params[:id])
  end
  
  def update
    @comment = Comment.find(params[:id])
    @comment.content = params[:content]
    @topic = @comment.topic_id
    if @comment.update(comment_params)
      redirect_to topic_path(@topic), success: 'コメントを更新しました'
    else
      flash.now[:danger] = "コメントの編集に失敗しました"
      render :edit
    end
  end
  
  def destroy
    comment = Comment.find_by(user_id: current_user.id, id: params[:comment_id])
    @topic = comment.topic_id
    comment.destroy
    redirect_to topic_path(@topic), danger: 'コメントを消去しました'
  end
  
  private
  def comment_params
    params.require(:comment).permit(:content, :topic_id, :user_id)
  end
  
  def edit_comment_params
    params.require(:comment).permit(:content, :id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Edit Comment</h1>
        <%= form_for @comment,url: comments_update_path do |f| %>
          <div class="form-group">
            <%= f.label :content %>
            <%= f.text_area :content, class: 'form-control' %>
            
          </div>

          <%= f.submit '編集する', class: 'btn btn-black btn-block' %>

        <% end %>
      </div>
    </div>
  </div>

app/views/comments/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Comment</h1>
        <%= form_for @comment,url: comments_create_path do |f| %>
          <div class="form-group">
            <%= f.label :content %>
            <%= f.text_area :content, class: 'form-control' %>
            <%= f.hidden_field :topic_id, :value => params[:topic_id] %>
          </div>

          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>

        <% end %>
      </div>
    </div>
  </div>