config/routes.rb
Rails.application.routes.draw do
  get 'topics/new'
  get 'sessions/new'
  
  root 'topics#index'
  
  resources :users
  
  get '/login',  to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :topics
  
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
  get '/comments/:topic_id/new' => 'comments#new', as: 'comments'
  post '/comments/:topic_id/create', to: 'comments#create', as:'comments_create'
  get '/comments/:id/edit', to: 'comments#edit', as:'edit_comments'
  patch '/comments/:id', to: 'comments#update', as: 'comments_update'
  delete '/comments', to: 'comments#destroy', as:'comment_delete'
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  #youtubeのみ許可
  validates :url, presence: true, 
                  format:{ with: /(youtu\.be\/|youtube.com\/watch\?(?=[^?]*v=\w+))(?:[^\s?]+)?\z/ , message: "無効なリンクです"}
  #/youtu/
  
  
  belongs_to :user
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  
  has_many :comments
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user, only:[:new, :edit, :destroy]
  
  
  def index
      #@topics = Topic.all.includes(:favorite_users, :comments)
      @topics = Topic.page(params[:page]).per(6).order(created_at: :desc).order(created_at: :desc)
      
  end
  
  def new
    @topic = Topic.new
  end
  
  def create
    @topic = current_user.topics.new(topic_params)
    
    if @topic.save
      redirect_to topics_path, success: '投稿しました'
    else
      flash.now[:danger] = "投稿できませんでした"
      render :new
    end
  end
  
  def show
    @topic = Topic.find(params[:id])
    @comments = @topic.comments
    
  end
  
  def edit
    @topic = Topic.find_by(id: params[:id])
  end
  def update
    @topic = Topic.find_by(id: params[:id])
    if @topic.update(topic_params)
      redirect_to topic_path(@topic), success: '投稿内容を更新しました'
    else
      flash.now[:danger] = "編集に失敗しました"
      render :edit
    end
  end
  
  def destroy
    topic = Topic.find_by(user_id: current_user.id, id: params[:id])
    topic.destroy
    redirect_to topics_path, danger: '投稿を消去しました'
  end
  
  private
  def topic_params
    params.require(:topic).permit(:url, :description)
  end
  
  
end

app/helpers/topics_helper.rb
module TopicsHelper
  
  def youtube_embed(youtube_url)
    if youtube_url[/youtu\.be\/([^\?]*)/]
        youtube_id = $1
    else
        # Regex from # https://stackoverflow.com/questions/3452546/javascript-regex-how-to-get-youtube-video-id-from-url/4811367#4811367
        youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
        youtube_id = $5
    end
    iframe = content_tag(
      :iframe,
      '', # empty body
      width: 600,
      height: 400,
      src: "https://www.youtube.com/embed/#{youtube_id}",
      frameborder: 0,
      allowfullscreen: true
    )
    content_tag(:div, iframe, class: 'youtube-container')
  
  end
  
  def youtube_vi(youtube_url)
    if youtube_url[/youtu\.be\/([^\?]*)/]
        youtube_id = $1
    else
        # Regex from # https://stackoverflow.com/questions/3452546/javascript-regex-how-to-get-youtube-video-id-from-url/4811367#4811367
        youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
        youtube_id = $5
    end
    iframe = content_tag(
      :iframe,
      '', # empty body
      width: 320,
      height: 180,
      src: "https://i.ytimg.com/vi/#{youtube_id}/mqdefault.jpg",
      frameborder: 0,
      allowfullscreen: true
    )
    content_tag(:div, iframe, class: 'youtube-container')
  
  end
  
end

app/views/topics/edit.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Edit Content</h1>
        <%= form_for @topic do |f| %>
          <div class="form-group">
            <%= f.label :url %>
            <%= f.text_field :url %>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>

          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="page_content">
	<div class="container">
  		<div class="row row-lg-eq-height">
  		  <div class="main_content">
  		    	<!-- Category -->
  
  					<div class="category">
  					  <div class="section_content">
  								<div class="grid clearfix">
  								  <!-- topic index -->
  								  <% @topics.each do |topic| %>  
    								  <div class="card card_small_with_image grid-item">
    										<%= youtube_vi(topic.url) %>
    										<div class="card-body">
    										  <p>URL:<%= raw Rinku.auto_link(h(topic.url)) %></p>
    											<div class="card-title card-title-small"><%= topic.description.truncate(30) %></div>
    											 <p><%= link_to "詳しくみる..", topic_path(topic.id) %></p>
    											<small class="post_meta"><%= topic.user.name %>
    											  <span><%= topic.created_at.strftime('%Y/%m/%d') %></span>
    											  <span>
        											<% if topic.favorite_users.include?(current_user) %>
                                <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                                  <%= fa_icon 'heart', style: 'color: red;' %>
                                <% end %>
                              <% else %>
                                <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                                  <%= fa_icon 'heart-o', style: 'color: black;' %>
                                <% end %>
                              <% end %>
                              <%= topic.favorite_users.count %>
                            </span>
                          </small>
    										</div>
    									</div>
  									<% end %>
  								</div>
  								<%= paginate(@topics) %>
  					  </div>
  					</div>
  		  </div>
  		</div>
	</div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Video</h1>
        <%= form_for @topic do |f| %>
          <div class="form-group">
            <%= f.label :url %>
            <%= f.text_field :url %>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>

          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<div class="page_content">
	<div class="container">
		<div class="row row-lg-eq-height">
		  <div class="col-lg-9">
				<div class="post_content">
				  
				  <!-- Top Panel -->
				  <div class="post_panel post_panel_top d-flex flex-row align-items-center justify-content-start">
				    <h2 class="post_name"><%= @topic.user.name %></h2><span><%= @topic.created_at.strftime('%Y/%m/%d') %></span>
				  </div>
				  
				  <div class="post_body">
				    <div class="post_main">
				      <%= youtube_embed(@topic.url) %>
				      <p>URL:<%= raw Rinku.auto_link(h(@topic.url)) %></p>
							<div class="icon-menus">
  							<% if @topic.favorite_users.include?(current_user) %>
                  <%= link_to favorites_path(topic_id: @topic.id), method: :delete do %>
                    <%= fa_icon 'heart 3x', style: 'color: red;' %>
                  <% end %>
                <% else %>
                  <%= link_to favorites_path(topic_id: @topic.id), method: :post do %>
                    <%= fa_icon 'heart-o 3x', style: 'color: black;' %>
                  <% end %>
                <% end %>
                <span class="icon"><%= @topic.favorite_users.count %></span>
              
                <%= link_to comments_path(topic_id: @topic.id) do %>
                  <%= fa_icon 'commenting-o 3x', style: 'color: black;', class: 'icon' %>
                <% end %>
                        
                <% if logged_in? && current_user.id == @topic.user_id %>
                  <%= link_to topic_path(id: @topic.id), method: :delete do %>
                    <%= fa_icon 'trash-o 3x', style: 'color: black;', class: 'icon' %>
                  <% end %>
                  
                  <p style="display: inline-block;"><%= link_to '編集する', edit_topic_path(id: @topic.id) %></p>
                  
                <% end %>
              </div>
              <div class="post_p"><%= @topic.description %></div>
						</div>
					</div>
		    </div>
		    
		    
			  <!-- Comments -->
				<div class="comments">
  					<div class="comments_title">Comments <span>(<%= @comments.count %>)</span></div>
  						<div class="row">
  							<div class="col-xl-8">
  							  <div class="comments_container">
    							   
    									<ul class="comment_list">
    									  <% @comments.each do |comment| %>
    										<li class="comment">
    											<div class="comment_body">
    												<div class="comment_panel d-flex flex-row align-items-center justify-content-start">
    													<small class="comment_meta"><%= comment.user.name %> : <span><%= comment.created_at.strftime('%Y/%m/%d %-H時%-M分') %></span></small>
    											  </div>
    												<div class="comment_content">
    													<p><%= comment.content %></p>
    												</div>
    												<div class="comment_edit">
      												<% if logged_in? && current_user.id == comment.user_id %>
                                <%= link_to comment_delete_path(comment_id: comment.id), method: :delete do %>
                                  <%= fa_icon 'trash-o', style: 'color: black;', class: 'icon' %>
                                <% end %>
                                <p style="display: inline-block;"><%= link_to '編集する', edit_comments_path(id: comment.id) %></p>
                              <% end %>
                            </div>
    											</div>
    										</li>
    										<% end %>
    									</ul>
    									
  								</div>
  						  </div>
  						</div>	
				  </div>
	   </div>
		</div>
	</div>
</div>