config/routes.rb
Rails.application.routes.draw do
  get 'topics/new'
  get 'sessions/new'
  
  root 'topics#index'
  
  resources :users
  
  get '/login',  to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :topics
  
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
  get '/comments/:topic_id/new' => 'comments#new', as: 'comments'
  post '/comments/:topic_id/create', to: 'comments#create', as:'comments_create'
  get '/comments/:id/edit', to: 'comments#edit', as:'edit_comments'
  patch '/comments/:id', to: 'comments#update', as: 'comments_update'
  delete '/comments', to: 'comments#destroy', as:'comment_delete'
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true,uniqueness: true, length: {maximum: 15}
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, length: {minimum: 5,maximum: 32},
                      format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i}
  
  
  has_secure_password
  
  has_many :topics
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: 'topic'
  
  has_many :comments
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only:[:edit, :destroy]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end
  
  def show
    @user = User.find_by(id: params[:id])
    @topics = @user.topics.order(created_at: :desc)
    
  end
  
  def edit
    @user = User.find_by(id: params[:id])
  end
  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), success: '登録内容を変更しました'
    else
      flash.now[:danger] = "登録内容を変更できませんでした"
      render :edit
    end
  end
  
  def destroy
    user = User.find_by(id: params[:id])
    user.destroy
    redirect_to root_path, danger: 'アカウントを消去しました'
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email,:password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="topic-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="offset-md-4 col-md-4 ">
        <h1 class="text-center ">Edit User profile</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          <%= f.submit "編集する", class: 'btn btn-black btn-block' %>
          <p class="user_delete"><%= link_to 'アカウントの消去', user_path(id: @user.id), method: :delete %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="offset-md-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign up</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path,class: 'text-white' %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row row-lg-eq-height">
		<div class="col-lg-8">
		  <div class="post_panel post_panel_top d-flex flex-row align-items-center justify-content-start">
				<h2 class="post_name">ユーザー情報</h2>
			</div>
    		<% if logged_in? && current_user.id == @user.id %>
    		  <table class="user_profile ">
    		    <tr>
    		      <th>User name(id):</th><td><%= @user.name %></td>
    		    </tr>
    		    <tr>
    		      <th>Your E-mail:</th><td><%= @user.email %></td>
    		    </tr>
    		  </table>
    		  <p class="edit_btn"><%= link_to '編集する', edit_user_path(id: @user.id) %></p>
    	  <% end %>
		</div>
	</div>
	
	
	<!--投稿遍歴一覧-->
	<div class="category">
  	<div class="section_content">
  	  <h2 class="post_name">過去にシェアした動画一覧</h2>
  		<div class="grid clearfix">
  		<!-- topic index -->
  			<% @topics.each do |topic| %>  
    		 <div class="card card_small_with_image grid-item">
    				<%= youtube_vi(topic.url) %>
    			  <div class="card-body">
    					<p>URL:<%= raw Rinku.auto_link(h(topic.url)) %></p>
  						<div class="card-title card-title-small"><%= topic.description.truncate(30) %></div>
    				  <p><%= link_to "詳しくみる..", topic_path(topic.id) %></p>
    					<small class="post_meta"><%= topic.user.name %>
      					<span><%= topic.created_at.strftime('%Y/%m/%d') %></span>
      					<span>
          				<% if topic.favorite_users.include?(current_user) %>
                    <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                      <%= fa_icon 'heart', style: 'color: red;' %>
                    <% end %>
                  <% else %>
                    <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                      <%= fa_icon 'heart-o', style: 'color: black;' %>
                    <% end %>
                  <% end %>
                  <%= topic.favorite_users.count %>
                </span>
              </small>
    				</div>
    			</div>
  			<% end %>
  		</div>
     </div>
    </div>
</div>