config/routes.rb
Rails.application.routes.draw do
  get 'topics/new'
  get 'sessions/new'
  
  root 'topics#index'
  
  resources :users
  
  get '/login',  to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :topics
  
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
  get '/comments/:topic_id/new' => 'comments#new', as: 'comments'
  post '/comments/:topic_id/create', to: 'comments#create', as:'comments_create'
  get '/comments/:id/edit', to: 'comments#edit', as:'edit_comments'
  patch '/comments/:id', to: 'comments#update', as: 'comments_update'
  delete '/comments', to: 'comments#destroy', as:'comment_delete'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PesCate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    
    
	<header class="header">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="header_content d-flex flex-row align-items-center justify-content-start ">
						<div class="logo"><%= link_to 'PES-CATE', topics_path %></div>
						<nav class="main_nav ml-auto">
							<ul>
							  <% if logged_in? %>
  								<li><%= link_to 'お気に入り一覧', favorites_index_path %></li>
  								<li><%= link_to '動画をシェア', new_topic_path %></li>
  								<li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
  								<li><%= link_to user_path(id: current_user.id) do %>
  									<%= fa_icon 'user-o' %>：<%= current_user.name %>
  								<% end %></li>
  							<% else %>
  								<li><%= link_to 'ユーザー登録', new_user_path  %></li>
  								<li><%= link_to 'ログイン', login_path %></li>
  								
								<% end %>
							</ul>
						</nav>
					
						<div class="hamburger ml-auto menu_mm">
							<i class="fa fa-bars trans_200 menu_mm" aria-hidden="true"></i>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>
  
  <!-- Menu -->

	<div class="menu d-flex flex-column align-items-end justify-content-start text-right menu_mm trans_400">
		<div class="menu_close_container"><div class="menu_close"><div></div><div></div></div></div>
		<div class="logo menu_mm"><a href="#">PES-CATE</a></div>
		
		<nav class="menu_nav">
			<ul class="menu_mm">
			  <% if logged_in? %>
				<li class="menu_mm"><%= link_to 'お気に入り一覧', favorites_index_path %></li>
				<li class="menu_mm"><%= link_to '動画をシェア', new_topic_path %></li>
				<li class="menu_mm"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
				<li><%= link_to user_path(id: current_user.id) do %>
  					<%= fa_icon 'user-o' %>：<%= current_user.name %>
  			<% end %></li>
				<% else %>
				<li class="menu_mm"><%= link_to 'ユーザー登録', new_user_path  %></li>
				<li class="menu_mm"><%= link_to 'ログイン', login_path %></li>
				<li class="menu_mm"><a href="#">Contact</a></li>
				<% end %>
			</ul>
		</nav>
	</div>
	
    <%= yield %>
    
    <script>
      $(function(){
        $(".alert").fadeOut(5000);
      });
      
      
    </script>
  </body>
</html>